name: my_chatapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  signalr_core: ^1.1.1
  http: ^0.13.6
  encrypt: ^5.0.3
  cryptography: ^2.7.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  flutter_webrtc: ^1.1.0
  shared_preferences: ^2.2.3 #تخزين حاجات بسيطه زي الوضع اليلي مفعل او لا
  sqflite: ^2.3.3+1
  path: ^1.9.0 #للروابط خصوصا الشرطه المايله .يعطي دوال

  path_provider: ^2.1.3 #"دليل" يخبرك بالمسارات الصحيحة والمسموح بها لتخزين الملفات على الجهاز
  uuid: ^4.4.0 #مولّد المعرّفات الفريدة
  intl: ^0.19.0 #كيف أعرض التواريخ والأرقام والعملات بالتنسيق الصحيح
  iconsax: ^0.0.8
  audioplayers: ^6.0.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.2
  flutter_callkit_incoming: ^2.0.3
  flutter_local_notifications: ^18.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test: #المكتبة الأساسية التي توفر إطار عمل الاختبار
    sdk: flutter
  flutter_lints: ^4.0.0 # يفرض عليك أسلوبًا جيدًا ونظيفًا للكتابة

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/audio/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
